name: example
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.16.0'
dependencies:
  extended_sliver: any
  ff_annotation_route_library: any
  fl_chart: any
  flutter:
    sdk: flutter

  http_client_helper: any
  image: any
  image_editor: any
  intl: any
  js: any
  like_button: any
  loading_more_list: any
  oktoast: any
  photo_manager: any
  pull_to_refresh_notification: any
  url_launcher: any
  vm_service: any
  wechat_assets_picker: any

dependency_overrides:
  extended_image:
    path: ../
  path_provider: ^2.0.15 
  photo_manager: 3.0.0-dev.1
  wechat_assets_picker: 8.9.0-dev.1
  # extended_image_library:
  #   path: ../../extended_image_library  
flutter:
  uses-material-design: true
  assets:
    - assets/
