name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 10.0.1
repository: https://github.com/fluttercandies/extended_image
issue_tracker: https://github.com/fluttercandies/extended_image/issues
topics:
  - image
  - cropper
  - photo-view
  - editor
  - slide-out

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  extended_image_library: ^5.0.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  vector_math: ^2.1.4
dependency_overrides:
  # extended_image_library:
  #   path: ../extended_image_library

