name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 4.0.0
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extended_image_library:
    git:
      url: https://github.com/fluttercandies/extended_image_library.git
  flutter:
    sdk: flutter
  meta: ^1.1.8

