name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 6.0.2+1
homepage: https://github.com/fluttercandies/extended_image

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.8.0'

dependencies:
  extended_image_library: ^3.1.2
  flutter:
    sdk: flutter
  meta: ^1.7.0
