name: No Free usage issue checker

on:
  issues:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Check issue actor
      uses: ./
      with:
        repo: $GITHUB_REPOSITORY
        user: $GITHUB_ACTOR
        token: ${{ secrets.GITHUB_TOKEN }}